apiVersion: v1
kind: Service
metadata:
  labels:
    run: my-nginx
  name: my-nginx
  namespace: sre-test
spec:
  type: ClusterIP
  ports:
    - name: web
      port: 8888
      targetPort: 80
    - name: exporter
      port: 9113
      targetPort: 9113
  selector:
    run: my-nginx

