apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  name: my-nginx
  namespace: sre-test
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      run: my-nginx
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
        - image: nginx/nginx-prometheus-exporter:0.11
          imagePullPolicy: Always
          name: my-nginx-exporter
          args:
            - "-nginx.scrape-uri=http://localhost:8080/stub_status"
          ports:
            - containerPort: 9113
              name: exporter
              protocol: TCP
        - image: nginx
          imagePullPolicy: Always
          name: my-nginx
          ports:
            - containerPort: 80
              name: web
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /usr/share/nginx/html/
              name: nginx-index-file
#            - mountPath: /etc/nginx/conf.d/default.conf
#              name: nginx-stub-conf
#              subPath: default.conf
            - mountPath: /etc/nginx/conf.d/stub-status.conf
              name: nginx-stub-conf
              subPath: stub-status.conf
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
      volumes:
        - configMap:
            defaultMode: 420
            name: nginx-cm-conf
          name: nginx-stub-conf

